######################################################################
# Automatically generated by qmake (2.01a) ?? 6? 8 15:11:56 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += sql

# Input
HEADERS += DB.h MainWindow.h MyRSA.h
FORMS += mainwindow.ui
SOURCES += DB.cpp main.cpp MainWindow.cpp MyRSA.cpp
